[default.deploy.parameters]
stack_name = "ewaste-optimizer"
resolve_s3 = true
s3_prefix = "ewaste-optimizer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=dev"
